# Bir özel kayıt defterinde depolanan bağımlılıkları güncellemek için minimum ayarlar

version: 2
registries:
  dockerhub: # Özel bir kayıt için erişimi tanımlayın
    type: docker-registry
    url: https://hub.docker.com
    username: ahmetcay
    password: ${{secrets.DOCKERHUB_PASSWORD}}
updates:
  - package-ecosystem: "docker"
    directory: "/docker-registry/dockerhub"
    registries:
      - dockerhub # Bu kayıt defterinde bağımlılıklar için sürüm güncellemelerine izin verin
    schedule:
      interval: "monthly"



////////////////////////////////////////////////////////////////////////////////////////



# Temel `dependabot.yml` dosyası ile
# İki paket yöneticisi için minimum yapılandırma

version: 2
updates:
  # Npm için sürüm güncellemelerini etkinleştirin
  - package-ecosystem: "npm"
    # 'package.json' ve 'package-lock.json' dosyaları için kök dizininde arayın
    directory: "/"
    # Her gün güncellemeler için npm kayıt defterini kontrol edin (hafta içi)
    schedule:
      interval: "daily"

  # Docker için sürüm güncellemelerini etkinleştirin
  - package-ecosystem: "docker"
    # 'Dockerfile' dosyası için kök dizininde arayın
    directory: "/"
    # Haftada bir kez güncellemeleri kontrol edin
    schedule:
      interval: "weekly"
