version: 2
updates:
  # NPM bağımlılıkları için yapılandırma
  - package-ecosystem: "npm"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "daily"  # Günlük güncelleme
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    ignore:
      - dependency-name: "node_modules"  # Node_modules klasörü yok say
    commit-message:
      prefix: "fix"  # Commit ön eki

  # PIP bağımlılıkları için yapılandırma
  - package-ecosystem: "pip"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "daily"  # Günlük güncelleme
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    ignore:
      - dependency-name: "venv"  # Sanal ortamı yok say
    commit-message:
      prefix: "fix"  # Commit ön eki

  # Ruby için Bundler yapılandırması
  - package-ecosystem: "bundler"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "daily"  # Günlük güncelleme
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit ön eki

  # Maven bağımlılıkları için yapılandırma
  - package-ecosystem: "maven"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "daily"  # Günlük güncelleme
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit ön eki

  # Yarn bağımlılıkları için yapılandırma
  - package-ecosystem: "yarn"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "daily"  # Günlük güncelleme
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit ön eki

  # Go modları için yapılandırma
  - package-ecosystem: "go_modules"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "daily"  # Günlük güncelleme
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit ön eki

  # Composer (PHP) bağımlılıkları için yapılandırma
  - package-ecosystem: "composer"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "daily"  # Günlük güncelleme
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit ön eki

  # Elixir için Hex bağımlılıkları yapılandırması
  - package-ecosystem: "hex"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "daily"  # Günlük güncelleme
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit ön eki

# Ekstra yapılandırma, dosya uzantıları veya özel hatalar içermemektedir.
