version: 2
updates:
  # Daily updates for playwright
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "playwright"
    versioning-strategy: increase

  # Weekly updates for specific libraries
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@noble*"
      - dependency-name: "fflate"
      - dependency-name: "tensorflow" # Including AI library for JavaScript
    versioning-strategy: increase
    groups:
      noble:
        applies-to: version-updates
        patterns:
          - "@noble*"
        update-types:
          - "minor"
          - "patch"

  # General npm updates excluding specific dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*"
    versioning-strategy: increase
    ignore:
      - dependency-name: "react"
      - dependency-name: "vue"

  # Python AI library updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "tensorflow" # AI library
      - dependency-name: "torch"      # Another AI library
      - dependency-name: "scikit-learn" # Machine learning library
    versioning-strategy: increase

  # Java updates, including AI libraries
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "deeplearning4j" # Java AI library
      - dependency-name: "*"
    versioning-strategy: increase

  # Ruby updates (using bundler)
  - package-ecosystem: "bundler" # Correct ecosystem for Ruby projects
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "tensorflow-ruby" # AI library for Ruby
    versioning-strategy: increase
