name: Dependabot CI

on:
  schedule:
    - cron: '*/15 * * * *'  # Her 15 dakikada bir çalışır
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Gerekli Node.js sürümünü buraya girin

      - name: Install dependencies
        run: |
          npm install  # npm bağımlılıklarını yükle

      - name: Run tests
        run: |
          npm test  # Testleri çalıştır

  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Gerekli Node.js sürümünü buraya girin

      - name: Install dependencies
        run: npm install  # npm bağımlılıklarını yükle

      - name: Update dependencies
        run: npm update  # Tüm bağımlılıkları güncelle

      - name: Commit changes
        run: |
          git config --local user.email "you@example.com"  # Git kullanıcı e-postanızı girin
          git config --local user.name "Your Name"  # Git kullanıcı adınızı girin
          git add .  # Güncellenen dosyaları ekle
          git commit -m "Chore: Update dependencies" || echo "No changes to commit"  # Güncellemeleri commit et
          git push origin main  # Güncellemeleri itme (branch adını kontrol edin)

  # Dependabot yapılandırması
  dependabot_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up package manager
        run: |
          # Bu kısımda birden fazla paket yöneticisi için gerekli şu komutları ekleyebilirsiniz.
          npm install  # npm bağımlılıklarını yükle
          pip install -r requirements.txt  # Python bağımlılıklarını yükle
          composer install  # PHP bağımlılıklarını yükle
          bundle install  # Ruby bağımlılıklarını yükle
          cd your-go-module-directory && go mod tidy  # Go bağımlılıklarını güncelleyebilirsiniz.

      - name: Run all tests
        run: |
          npm test  # npm testlerini çalıştır
          pytest  # Python testlerini çalıştır
          bundle exec rake test  # Ruby testlerini çalıştır
