# Bir özel kayıt defterinde depolanan bağımlılıkları güncellemek için minimum ayarlar

versiyon: 2
Kayıtlar:
  Dockerhub: # Özel bir kayıt için erişimi tanımlayın
    tip: docker-registir
    url: kayıt.hub.docker.com
    kullanıcı adı: ahtaçayı
    Şifre: ${{secrets.DOCKERHUB_PASSWORD}}
Güncellemeler:
  - paket ekosistemi: "docker"
    Dizin: "/docker-registry/dockerhub"
    Kayıtlar:
      - dockerhub # Bu kayıt defterinde bağımlılıklar için sürüm güncellemelerine izin verin
    Program:
      aralık: "aylık"



////////////////////////////////////////////////////////////////////////////////////////



# Temel `dependabot.yml` dosyası ile
# İki paket yöneticisi için minimum yapılandırma

versiyon: 2
Güncellemeler:
  # Npm için sürüm güncellemelerini etkinleştirin
  - paket ekosistem: "npm"
    # 'propage.json' ve 'kresim'deki 'krep' dosyası' için 'krediye' dizininde' arayın
    Dizin: "/"
    # Her gün güncellemeler için npm kayıt defterini kontrol edin (hafta içi)
    Program:
      aralık: "güneyim"

  # Docker için sürüm güncellemelerini etkinleştirin
  - paket ekosistemi: "docker"
    # 'Yık Çanta' içinde 'köklü" dizininde bir 'Dockerfile' arayın
    Dizin: "/"
    # Haftada bir kez güncellemeleri kontrol edin
    Program:
      aralık: "haftalık"

