version: 2
updates:
  # NPM bağımlılıkları için yapılandırma
  - package-ecosystem: "npm"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "every-15-minutes"  # Her 15 dakikada bir güncelle
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    ignore:
      - dependency-name: "node_modules"  # Node_modules klasörü yok say
    commit-message:
      prefix: "fix"  # Commit mesajı için ön ek
    versioning-strategy: "increase"  # Sürüm numarasını artırmak için strateji

  # PIP bağımlılıkları için yapılandırma
  - package-ecosystem: "pip"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "every-15-minutes"  # Her 15 dakikada bir güncelle
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    ignore:
      - dependency-name: "venv"  # Sanal ortamı yok say
    commit-message:
      prefix: "fix"  # Commit mesajı için ön ek
    versioning-strategy: "increase"  # Sürüm numarasını artırmak için strateji

  # Ruby için Bundler yapılandırması
  - package-ecosystem: "bundler"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "every-15-minutes"  # Her 15 dakikada bir güncelle
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit mesajı için ön ek
    versioning-strategy: "increase"  # Sürüm numarasını artırmak için strateji

  # Maven bağımlılıkları için yapılandırma
  - package-ecosystem: "maven"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "every-15-minutes"  # Her 15 dakikada bir güncelle
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit mesajı için ön ek
    versioning-strategy: "increase"  # Sürüm numarasını artırmak için strateji

  # Yarn bağımlılıkları için yapılandırma
  - package-ecosystem: "yarn"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "every-15-minutes"  # Her 15 dakikada bir güncelle
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit mesajı için ön ek
    versioning-strategy: "increase"  # Sürüm numarasını artırmak için strateji

  # Go modları için yapılandırma
  - package-ecosystem: "go_modules"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "every-15-minutes"  # Her 15 dakikada bir güncelle
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit mesajı için ön ek
    versioning-strategy: "increase"  # Sürüm numarasını artırmak için strateji

  # Composer (PHP) bağımlılıkları için yapılandırma
  - package-ecosystem: "composer"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "every-15-minutes"  # Her 15 dakikada bir güncelle
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit mesajı için ön ek
    versioning-strategy: "increase"  # Sürüm numarasını artırmak için strateji

  # Elixir için Hex bağımlılıkları yapılandırması
  - package-ecosystem: "hex"
    directory: "/"  # Projenin kök dizini
    schedule:
      interval: "every-15-minutes"  # Her 15 dakikada bir güncelle
    allow:
      - dependency-name: "*.*"  # Tüm bağımlılıklar
    commit-message:
      prefix: "fix"  # Commit mesajı için ön ek
    versioning-strategy: "increase"  # Sürüm numarasını artırmak için strateji

# Ekstra özellikler:
# Bu yapılandırma, tüm bağımlılık yöneticilerini kapsayıcı ve otomatik güncellemeler ile birlikte oluşturulmuştur.
