version: 2
registries:
  example:
    type: npm-registry
    url: https://example.com
    token: ${{secrets.NPM_TOKEN}}

updates:
  - package-ecosystem: "npm"
    directory: "/src/npm-project"  # NPM projesinin dizini
    schedule:
      interval: "daily"  # Günlük güncelleme kontrolü
    ignore:
      - dependency-name: "lodash"  # Lodash için tüm güncellemeleri göz ardı et
    open-pull-requests-limit: 5  # Maksimum 5 açık PR
    registries:
      - example  # Özel kayıt defteri

  - package-ecosystem: "gomod"
    directory: "/"  # Go projesinin dizini
    schedule:
      interval: "daily"  # Günlük güncelleme kontrolü
    groups:
      golang:
        applies-to: security-updates  # Sadece güvenlik güncellemeleri için
        patterns:
          - "golang.org*"  # Golang bağımlılık desenleri
