name: Dependabot CI

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependency_management:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake # Tools for C++ development

      - name: Find Projects
        id: find-projects
        run: |
          echo "Project directories:"
          for dir in $(find . -type d -name "nodejs-app" -o -name "python-app" -o -name "ruby-app" -o -name "php-app" -o -name "java-app" -o -name "go-app" -o -name "dotnet-app" -o -name "cpp-app" -o -name "swift-app" -o -name "rust-app" -o -name "typescript-app" -o -name "elixir-app" -o -name "scala-app"); do
            echo "Found project: $dir"
            echo "$dir" >> projects.txt
          done
          cat projects.txt

      - name: Node.js Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f package.json ]; then
                npm install
                npm update
                npm audit fix
                npx eslint . --fix || true
              fi
              cd -
            fi
          done < projects.txt

      - name: Python Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f requirements.txt ]; then
                pip install -r requirements.txt
                pip install --upgrade -r requirements.txt
                pip install safety black flake8
                safety check
                black . || true
                flake8 . || true
              fi
              cd -
            fi
          done < projects.txt

      - name: Ruby Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f Gemfile ]; then
                bundle install
                bundle update
                bundler-audit check
                rubocop -A || true
              fi
              cd -
            fi
          done < projects.txt

      - name: PHP Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f composer.json ]; then
                composer install
                composer update
                composer audit
                php-cs-fixer fix || true
              fi
              cd -
            fi
          done < projects.txt

      - name: Java Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f pom.xml ]; then
                mvn install
                mvn versions:use-latest-releases
                mvn checkstyle:check || true
                mvn spotless:apply || true
              fi
              cd -
            fi
          done < projects.txt

      - name: Go Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f go.mod ]; then
                go mod tidy
                go vet ./... || true
                gofmt -w . 
              fi
              cd -
            fi
          done < projects.txt

      - name: C# Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f *.csproj ]; then
                dotnet restore
                dotnet outdated
                dotnet tool install -g dotnet-format
                dotnet format --check || true
                dotnet build
              fi
              cd -
            fi
          done < projects.txt

      - name: C++ Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              mkdir -p build
              cd build
              cmake ..
              make
              cppcheck .. 
              cd -
            fi
          done < projects.txt

      - name: Swift Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f Package.swift ]; then
                swift package resolve
                swift test
                swiftformat . 
              fi
              cd -
            fi
          done < projects.txt

      - name: Rust Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f Cargo.toml ]; then
                cargo update
                cargo fmt --all -- --check || true 
                cargo clippy -- -D warnings || true
              fi
              cd -
            fi
          done < projects.txt

      - name: TypeScript Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f package.json ]; then
                npm install
                npm update
                npm audit fix
                npx eslint . --fix || true
              fi
              cd -
            fi
          done < projects.txt

      - name: Elixir Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f mix.exs ]; then
                mix deps.get
                mix deps.update --all
                mix format || true
              fi
              cd -
            fi
          done < projects.txt

      - name: Scala Dependency Management
        run: |
          while IFS= read -r line; do
            if [[ -d "$line" ]]; then
              cd "$line" || exit
              if [ -f build.sbt ]; then
                sbt update
                sbt scalafmt || true
              fi
              cd -
            fi
          done < projects.txt

      - name: Commit Changes with GPG Signing
        run: |
          git config --local user.email "gamestime102@users.noreply.github.com"  # Git user email
          git config --local user.name "gamestime102"  # Git user name
          git config --local commit.gpgSign true  # Enable GPG signing for commits
          git add .  # Add updated files
          git commit -m "Chore: Update dependencies and format code" || echo "No changes to commit"
          git push origin main  # Push changes to the main branch

      - name: Commit Changes with GPG Signing
        run: |
          git config --local user.email "gamestime102-tv@users.noreply.github.com"  # Git user email
          git config --local user.name "gamestime102tv"  # Git user name
          git config --local commit.gpgSign true  # Enable GPG signing for commits
          git add .  # Add updated files
          git commit -m "Chore: Update dependencies and format code" || echo "No changes to commit"
          git push origin main  # Push changes to the main branch
          
      - name: Create Version Tag (Auto Version Bump)
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')  # Generate a unique version based on the timestamp
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"  # Push the tag to the remote

      - name: Complete
        run: echo "SUCCESSFULLY COMPLETED"

      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The workflow has completed successfully."}' https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The workflow has failed."}' https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
