# Bir özel kayıt defterinde depolanan bağımlılıkları güncellemek için minimum ayarlar

version: 2
registries:
  dockerhub: # Özel bir kayıt için erişimi tanımlayın
    type: docker-registry
    url: https://hub.docker.com
    username: ahmetcay
    password: ${{secrets.DOCKERHUB_PASSWORD}}
  npm_registry: # Npm kayıt defteri için erişimi tanımlayın
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_TOKEN}}

updates:
  - package-ecosystem: "docker"
    directory: "/docker-registry/dockerhub"
    registries:
      - dockerhub # Bu kayıt defterinde bağımlılıklar için sürüm güncellemelerine izin verin
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "docker"
      prefix-development: "dev-docker"
      include: scope

  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm_registry
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
      prefix-development: "dev-npm"
      include: scope
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "lodash"
        versions: ["4.17.21"]
    rebase-strategy: "auto"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      prefix-development: "dev-docker"
      include: scope

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions"
      prefix-development: "dev-actions"
      include: scope
    open-pull-requests-limit: 5

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "bundler"
      prefix-development: "dev-bundler"
      include: scope
    open-pull-requests-limit: 5
