version: 2
updates:
  # NPM Updates
  - package-ecosystem: "npm"
    directory: "/"  # Root directory
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"  # All NPM dependencies
    ignore:
      - dependency-name: "react"  # Ignore updates for React
      - dependency-name: "vue"
    target-branch: "main"  # Main branch
    commit-message:
      prefix: "fix"  # Prefix for commit message
    versioning-strategy: "auto"  # Automatic version updates

  # Weekly specific NPM dependency updates
  - package-ecosystem: "npm"
    directory: "/src"  # Subdirectory
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@noble*"
      - dependency-name: "fflate"
      - dependency-name: "playwright"
    target-branch: "feature/new-feature"  # Custom branch
    commit-message:
      prefix: "feat"  # Prefix for commit message

  # Python Updates
  - package-ecosystem: "pip"
    directory: "/"  
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"  # All Python dependencies
    ignore:
      - dependency-name: "tensorflow"
      - dependency-name: "torch"
    target-branch: "main"  
    commit-message:
      prefix: "fix"  # Prefix for commit message

  # Weekly updates for Python AI libraries
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "tensorflow"
      - dependency-name: "scikit-learn"
    target-branch: "feature/ai-updates"
    commit-message:
      prefix: "feat"

  # Ruby Updates
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"  # All Ruby dependencies
    target-branch: "main"
    commit-message:
      prefix: "fix"

  # Java Updates
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"  # All Java dependencies
    target-branch: "main"
    commit-message:
      prefix: "fix"
