version: 2
updates:
  # NPM Güncellemeleri
  - package-ecosystem: "npm"
    directory: "/"  # Proje ana dizini
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"  # Tüm NPM bağımlılıkları
    ignore:
      - dependency-name: "react"  # Güncellemeleri yok say
      - dependency-name: "vue"
    target-branch: "main"  # Ana dal
    commit-message:
      prefix: "fix"  # Commit mesajının başına "fix" ekle
    versioning-strategy: "auto"  # Otomatik sürüm güncellemeleri

  # Haftalık belirli NPM bağımlılık güncellemeleri
  - package-ecosystem: "npm"
    directory: "/src"  # Alt dizin
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@noble*"
      - dependency-name: "fflate"
      - dependency-name: "playwright"
    target-branch: "feature/new-feature"  # Özelleştirilmiş dal
    commit-message:
      prefix: "feat"  # Commit mesajının başına "feat" ekle

  # Python Güncellemeleri
  - package-ecosystem: "pip"
    directory: "/"  
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"  # Tüm Python bağımlılıkları
    ignore:
      - dependency-name: "tensorflow"
      - dependency-name: "torch"
    target-branch: "main"  
    commit-message:
      prefix: "fix"  # Commit mesajının başına "fix" ekle

  # Python AI kütüphaneleri için haftalık güncellemeler
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "tensorflow"
      - dependency-name: "scikit-learn"
    target-branch: "feature/ai-updates"
    commit-message:
      prefix: "feat"

  # Ruby Güncellemeleri
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"  # Tüm Ruby bağımlılıkları
    target-branch: "main"
    commit-message:
      prefix: "fix"

  # Java Güncellemeleri
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"  # Tüm Java bağımlılıkları
    target-branch: "main"
    commit-message:
      prefix: "fix"
